version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: news_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"
    volumes:
      - news_pgdata:/var/lib/postgresql/data
volumes:
  news_pgdata:
